import { Contract } from '@/types';
import { mockProperties } from './properties';
import { mockClients } from './clients';
import { mockAdvisor } from './advisor';

const now = new Date();
const addDays = (d: Date, days: number) => new Date(d.getTime() + days * 86400000);

export const mockContracts: Contract[] = [
  {
    id: 'contract-1',
    propertyId: 'prop-3',
    property: mockProperties[2],
    tenantId: 'client-2',
    tenant: mockClients[1],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    startDate: new Date('2023-12-01'),
    endDate: new Date('2024-11-30'),
    monthlyRent: 2500000,
    deposit: 5000000,
    paymentDay: 5,
    annualIncrease: 10,
    status: 'ACTIVE',
    notes: 'Contrato anual con opción de renovación',
    createdAt: new Date('2023-11-20'),
  },
  {
    id: 'contract-2',
    propertyId: 'prop-9',
    property: mockProperties[8],
    tenantId: 'client-7',
    tenant: mockClients[6],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    startDate: new Date('2023-10-01'),
    endDate: new Date('2024-09-30'),
    monthlyRent: 2200000,
    deposit: 4400000,
    paymentDay: 1,
    annualIncrease: 10,
    status: 'ACTIVE',
    notes: 'Familia con niños, buen historial de pago',
    createdAt: new Date('2023-09-25'),
  },
  {
    id: 'contract-3',
    propertyId: 'prop-8',
    property: mockProperties[7],
    tenantId: 'client-5',
    tenant: mockClients[4],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    startDate: addDays(now, -335),
    endDate: addDays(now, 22),
    monthlyRent: 1800000,
    deposit: 3600000,
    paymentDay: 10,
    annualIncrease: 10,
    status: 'ACTIVE',
    notes: 'Vence pronto - gestionar renovación',
    createdAt: addDays(now, -340),
  },
  {
    id: 'contract-4',
    propertyId: 'prop-12',
    property: mockProperties[11],
    tenantId: 'client-2',
    tenant: mockClients[1],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    startDate: addDays(now, -355),
    endDate: addDays(now, 12),
    monthlyRent: 1350000,
    deposit: 2700000,
    paymentDay: 15,
    annualIncrease: 10,
    status: 'ACTIVE',
    notes: 'Próximo a vencer - contactar inquilino',
    createdAt: addDays(now, -360),
  },
  {
    id: 'contract-5',
    propertyId: 'prop-7',
    property: mockProperties[6],
    tenantId: 'client-10',
    tenant: mockClients[9],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    startDate: new Date('2024-01-01'),
    endDate: new Date('2024-12-31'),
    monthlyRent: 12000000,
    deposit: 24000000,
    paymentDay: 1,
    annualIncrease: 8,
    status: 'ACTIVE',
    notes: 'Empresa de logística, contrato comercial',
    createdAt: new Date('2023-12-20'),
  },
  {
    id: 'contract-6',
    propertyId: 'prop-11',
    property: mockProperties[10],
    tenantId: 'client-5',
    tenant: mockClients[4],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    startDate: new Date('2022-08-01'),
    endDate: new Date('2023-07-31'),
    monthlyRent: 1400000,
    deposit: 2800000,
    paymentDay: 5,
    annualIncrease: 10,
    status: 'EXPIRED',
    notes: 'No renovó, se mudó al prop-8',
    createdAt: new Date('2022-07-20'),
  },
  {
    id: 'contract-7',
    propertyId: 'prop-1',
    property: mockProperties[0],
    tenantId: 'client-4',
    tenant: mockClients[3],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    startDate: addDays(now, 30),
    endDate: addDays(now, 395),
    monthlyRent: 3200000,
    deposit: 6400000,
    paymentDay: 5,
    annualIncrease: 10,
    status: 'DRAFT',
    notes: 'Pendiente de firma de ambas partes',
    createdAt: addDays(now, -2),
  },
  {
    id: 'contract-8',
    propertyId: 'prop-10',
    property: mockProperties[9],
    tenantId: 'client-10',
    tenant: mockClients[9],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    startDate: new Date('2023-03-01'),
    endDate: new Date('2024-02-29'),
    monthlyRent: 3800000,
    deposit: 7600000,
    paymentDay: 1,
    annualIncrease: 10,
    status: 'ACTIVE',
    notes: 'Renovado por 6 meses adicionales',
    createdAt: new Date('2023-02-15'),
  },
];

export async function getContracts(): Promise<Contract[]> {
  return mockContracts;
}
