import { Property } from '@/types';
import { mockAdvisor } from './advisor';
import { mockClients } from './clients';

export const mockProperties: Property[] = [
  {
    id: 'prop-1',
    code: 'POB-001',
    title: 'Apartamento moderno en El Poblado',
    description: 'Hermoso apartamento con acabados de lujo en el corazón de El Poblado. Iluminación natural, cocina integral y terraza privada con vista a la ciudad.',
    type: 'APARTMENT',
    operation: 'RENT',
    status: 'AVAILABLE',
    price: 3200000,
    adminFee: 280000,
    area: 85,
    rooms: 3,
    bathrooms: 2,
    parking: true,
    floor: 8,
    stratum: 6,
    address: 'Calle 10 # 43-20, El Poblado',
    neighborhood: 'El Poblado',
    city: 'Medellín',
    latitude: 6.2086,
    longitude: -75.5659,
    amenities: ['Piscina', 'Gimnasio', 'Salón comunal', 'Portería 24h', 'Zona BBQ'],
    images: [
      { id: 'img-1-1', url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800', alt: 'Sala principal' },
      { id: 'img-1-2', url: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800', alt: 'Cocina' },
      { id: 'img-1-3', url: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800', alt: 'Habitación principal' },
    ],
    ownerId: 'client-1',
    owner: mockClients[0],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'prop-2',
    code: 'LAU-002',
    title: 'Casa familiar en Laureles',
    description: 'Amplia casa de dos plantas en el mejor sector de Laureles. Jardín frontal y posterior, garaje doble y cuarto de servicio.',
    type: 'HOUSE',
    operation: 'SALE',
    status: 'AVAILABLE',
    price: 850000000,
    area: 220,
    rooms: 4,
    bathrooms: 3,
    parking: true,
    floor: 1,
    stratum: 5,
    address: 'Circular 76 # 34-15, Laureles',
    neighborhood: 'Laureles',
    city: 'Medellín',
    amenities: ['Jardín', 'Garaje doble', 'Cuarto de servicio', 'Zona de lavandería'],
    images: [
      { id: 'img-2-1', url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800', alt: 'Fachada' },
      { id: 'img-2-2', url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800', alt: 'Sala' },
    ],
    ownerId: 'client-3',
    owner: mockClients[2],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    createdAt: new Date('2023-10-15'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'prop-3',
    code: 'ENV-003',
    title: 'Apartamento en Envigado con vista panorámica',
    description: 'Moderno apartamento en Envigado con vista panorámica al valle del Aburrá. Piso 12, totalmente remodelado.',
    type: 'APARTMENT',
    operation: 'RENT',
    status: 'RENTED',
    price: 2500000,
    adminFee: 220000,
    area: 72,
    rooms: 2,
    bathrooms: 2,
    parking: true,
    floor: 12,
    stratum: 5,
    address: 'Carrera 43 # 48 Sur-50, Envigado',
    neighborhood: 'Envigado',
    city: 'Envigado',
    amenities: ['Piscina', 'BBQ', 'Portería 24h'],
    images: [
      { id: 'img-3-1', url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800', alt: 'Vista panorámica' },
      { id: 'img-3-2', url: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800', alt: 'Sala comedor' },
    ],
    ownerId: 'client-1',
    owner: mockClients[0],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    createdAt: new Date('2023-06-20'),
    updatedAt: new Date('2023-12-01'),
  },
  {
    id: 'prop-4',
    code: 'SAB-004',
    title: 'Casa nueva en Sabaneta',
    description: 'Proyecto nuevo en Sabaneta, sector Los Jardines. Excelente distribución y acabados modernos.',
    type: 'HOUSE',
    operation: 'SALE',
    status: 'NEGOTIATION',
    price: 620000000,
    area: 160,
    rooms: 3,
    bathrooms: 3,
    parking: true,
    floor: 1,
    stratum: 4,
    address: 'Calle 77 Sur # 42-10, Sabaneta',
    neighborhood: 'Sabaneta',
    city: 'Sabaneta',
    amenities: ['Jardín privado', 'Cocina integral', 'Closets en madera'],
    images: [
      { id: 'img-4-1', url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800', alt: 'Fachada' },
      { id: 'img-4-2', url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800', alt: 'Cocina' },
    ],
    ownerId: 'client-6',
    owner: mockClients[5],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: 'prop-5',
    code: 'BEL-005',
    title: 'Local comercial en Belén',
    description: 'Local comercial en zona de alto tráfico peatonal en Belén. Ideal para restaurante o comercio.',
    type: 'LOCAL',
    operation: 'RENT',
    status: 'AVAILABLE',
    price: 4500000,
    adminFee: 150000,
    area: 120,
    parking: false,
    floor: 1,
    stratum: 3,
    address: 'Carrera 76 # 32-45, Belén',
    neighborhood: 'Belén',
    city: 'Medellín',
    amenities: ['Baño incluido', 'Bodega pequeña', 'Vitrina doble'],
    images: [
      { id: 'img-5-1', url: 'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800', alt: 'Fachada local' },
    ],
    ownerId: 'client-6',
    owner: mockClients[5],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    createdAt: new Date('2023-11-20'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'prop-6',
    code: 'POB-006',
    title: 'Penthouse en El Poblado',
    description: 'Espectacular penthouse de 200m² en la mejor zona de El Poblado. Terraza de 80m² con jacuzzi y vista 360°.',
    type: 'APARTMENT',
    operation: 'SALE',
    status: 'AVAILABLE',
    price: 1800000000,
    area: 200,
    rooms: 4,
    bathrooms: 4,
    parking: true,
    floor: 20,
    stratum: 6,
    address: 'Calle 10 # 32-65, El Poblado',
    neighborhood: 'El Poblado',
    city: 'Medellín',
    amenities: ['Terraza privada', 'Jacuzzi', 'Concierge', 'Spa', 'Gimnasio privado'],
    images: [
      { id: 'img-6-1', url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800', alt: 'Sala principal' },
      { id: 'img-6-2', url: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800', alt: 'Terraza' },
    ],
    ownerId: 'client-3',
    owner: mockClients[2],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    createdAt: new Date('2023-08-01'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: 'prop-7',
    code: 'ITG-007',
    title: 'Bodega industrial en Itagüí',
    description: 'Bodega industrial de 800m² en zona franca de Itagüí. Altura libre 8m, piso industrial reforzado.',
    type: 'WAREHOUSE',
    operation: 'RENT',
    status: 'AVAILABLE',
    price: 12000000,
    area: 800,
    parking: true,
    floor: 1,
    stratum: 2,
    address: 'Carrera 52 # 33-20, Itagüí',
    neighborhood: 'Itagüí',
    city: 'Itagüí',
    amenities: ['Cargue y descargue', 'Oficina administrativa', 'Baños', 'Seguridad'],
    images: [
      { id: 'img-7-1', url: 'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800', alt: 'Bodega' },
    ],
    ownerId: 'client-8',
    owner: mockClients[7],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    createdAt: new Date('2023-07-10'),
    updatedAt: new Date('2024-01-08'),
  },
  {
    id: 'prop-8',
    code: 'LAM-008',
    title: 'Apartamento en La América',
    description: 'Apartamento bien ubicado en La América, cerca de centros comerciales y vías principales. Buena distribución.',
    type: 'APARTMENT',
    operation: 'RENT',
    status: 'AVAILABLE',
    price: 1800000,
    adminFee: 180000,
    area: 65,
    rooms: 3,
    bathrooms: 2,
    parking: false,
    floor: 4,
    stratum: 3,
    address: 'Carrera 65 # 44-50, La América',
    neighborhood: 'La América',
    city: 'Medellín',
    amenities: ['Salón comunal', 'Portería'],
    images: [
      { id: 'img-8-1', url: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800', alt: 'Sala' },
      { id: 'img-8-2', url: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800', alt: 'Cocina' },
    ],
    ownerId: 'client-1',
    owner: mockClients[0],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'prop-9',
    code: 'ROB-009',
    title: 'Casa en Robledo con jardín',
    description: 'Acogedora casa en Robledo con gran jardín interior y vista verde. Tranquilidad y naturaleza en la ciudad.',
    type: 'HOUSE',
    operation: 'RENT',
    status: 'RENTED',
    price: 2200000,
    adminFee: 100000,
    area: 140,
    rooms: 3,
    bathrooms: 2,
    parking: true,
    floor: 1,
    stratum: 3,
    address: 'Calle 105 # 57-30, Robledo',
    neighborhood: 'Robledo',
    city: 'Medellín',
    amenities: ['Jardín interior', 'Patio', 'Zona de lavandería'],
    images: [
      { id: 'img-9-1', url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800', alt: 'Fachada' },
    ],
    ownerId: 'client-6',
    owner: mockClients[5],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    createdAt: new Date('2023-04-15'),
    updatedAt: new Date('2023-10-01'),
  },
  {
    id: 'prop-10',
    code: 'BEL-010',
    title: 'Oficina en Belén Centro',
    description: 'Oficina moderna en edificio corporativo de Belén. Ideal para empresa pequeña o mediana.',
    type: 'OFFICE',
    operation: 'RENT',
    status: 'AVAILABLE',
    price: 3800000,
    adminFee: 350000,
    area: 95,
    rooms: 3,
    bathrooms: 2,
    parking: true,
    floor: 5,
    stratum: 4,
    address: 'Carrera 76 # 28-10, Belén',
    neighborhood: 'Belén',
    city: 'Medellín',
    amenities: ['Recepción', 'Sala de reuniones', 'Cocineta', 'Parqueadero visitantes'],
    images: [
      { id: 'img-10-1', url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800', alt: 'Oficina' },
    ],
    ownerId: 'client-8',
    owner: mockClients[7],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: 'prop-11',
    code: 'ENV-011',
    title: 'Apartamento estudio en Envigado',
    description: 'Cómodo apartamento estudio ideal para profesional o pareja. Ubicado cerca de la alcaldía de Envigado.',
    type: 'APARTMENT',
    operation: 'RENT',
    status: 'AVAILABLE',
    price: 1500000,
    adminFee: 120000,
    area: 42,
    rooms: 1,
    bathrooms: 1,
    parking: false,
    floor: 3,
    stratum: 4,
    address: 'Calle 40 Sur # 40-80, Envigado',
    neighborhood: 'Envigado',
    city: 'Envigado',
    amenities: ['Cocina integral', 'Portería'],
    images: [
      { id: 'img-11-1', url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800', alt: 'Estudio' },
    ],
    ownerId: 'client-3',
    owner: mockClients[2],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'prop-12',
    code: 'BEL-012',
    title: 'Apartamento familiar Bello Norte',
    description: 'Amplio apartamento en Bello con excelente ubicación, cerca al metro. Ideal para familia.',
    type: 'APARTMENT',
    operation: 'RENT',
    status: 'AVAILABLE',
    price: 1350000,
    adminFee: 130000,
    area: 78,
    rooms: 3,
    bathrooms: 2,
    parking: true,
    floor: 6,
    stratum: 3,
    address: 'Carrera 48 # 55-30, Bello',
    neighborhood: 'Bello',
    city: 'Bello',
    amenities: ['Zona infantil', 'Salón comunal', 'Portería 24h'],
    images: [
      { id: 'img-12-1', url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800', alt: 'Apartamento' },
    ],
    ownerId: 'client-1',
    owner: mockClients[0],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    createdAt: new Date('2024-01-28'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'prop-13',
    code: 'CAS-013',
    title: 'Casa en Castilla sector industrial',
    description: 'Casa usada en buen estado en Castilla, sector tranquilo. Dos plantas con patio.',
    type: 'HOUSE',
    operation: 'SALE',
    status: 'SOLD',
    price: 320000000,
    area: 130,
    rooms: 4,
    bathrooms: 2,
    parking: true,
    floor: 1,
    stratum: 2,
    address: 'Calle 98 # 68-45, Castilla',
    neighborhood: 'Castilla',
    city: 'Medellín',
    amenities: ['Patio', 'Zona de lavandería'],
    images: [
      { id: 'img-13-1', url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800', alt: 'Casa' },
    ],
    ownerId: 'client-8',
    owner: mockClients[7],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    createdAt: new Date('2023-05-12'),
    updatedAt: new Date('2023-09-30'),
  },
  {
    id: 'prop-14',
    code: 'POB-014',
    title: 'Apartamento amoblado El Poblado',
    description: 'Apartamento totalmente amoblado y equipado en El Poblado. Perfecto para ejecutivos o estadías cortas/largas.',
    type: 'APARTMENT',
    operation: 'RENT_SALE',
    status: 'AVAILABLE',
    price: 4500000,
    adminFee: 300000,
    area: 90,
    rooms: 2,
    bathrooms: 2,
    parking: true,
    floor: 15,
    stratum: 6,
    address: 'Avenida El Poblado # 14-100, El Poblado',
    neighborhood: 'El Poblado',
    city: 'Medellín',
    amenities: ['Amoblado', 'Piscina', 'Gimnasio', 'Sauna', 'Concierge'],
    images: [
      { id: 'img-14-1', url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800', alt: 'Sala' },
      { id: 'img-14-2', url: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800', alt: 'Habitación' },
    ],
    ownerId: 'client-3',
    owner: mockClients[2],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-03-25'),
  },
  {
    id: 'prop-15',
    code: 'LAU-015',
    title: 'Oficina premium Laureles',
    description: 'Oficina premium en edificio inteligente en Laureles. Tecnología de punta, excelente iluminación natural.',
    type: 'OFFICE',
    operation: 'RENT',
    status: 'PAUSED',
    price: 5200000,
    adminFee: 480000,
    area: 140,
    rooms: 4,
    bathrooms: 2,
    parking: true,
    floor: 9,
    stratum: 5,
    address: 'Circular 4 # 65-30, Laureles',
    neighborhood: 'Laureles',
    city: 'Medellín',
    amenities: ['Sala de juntas', 'Recepción', 'Cafetería', 'Parqueadero doble', 'Terraza corporativa'],
    images: [
      { id: 'img-15-1', url: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800', alt: 'Oficina' },
    ],
    ownerId: 'client-6',
    owner: mockClients[5],
    advisorId: 'advisor-1',
    advisor: mockAdvisor,
    createdAt: new Date('2023-10-01'),
    updatedAt: new Date('2024-01-30'),
  },
];

export async function getProperties(): Promise<Property[]> {
  return mockProperties;
}
